inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - spec/fixtures/**/*
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
